package com.elementtimes.elementtimes.common.fluid;

import net.minecraftforge.fluids.ForgeFlowingFluid;

/**
 * 流体组分

 */
public class FluidProperties {
    public static ForgeFlowingFluid.Properties Steel = new ForgeFlowingFluid.Properties(() -> Sources.Steel, () -> Flowings.steel, AttrBuilders.steel).bucket(() -> Buckets.steel).block(() -> FluidBlocks.fluidSteel);
    public static ForgeFlowingFluid.Properties Fe = new ForgeFlowingFluid.Properties(() -> Sources.Fe, () -> Flowings.Fe, AttrBuilders.Fe).bucket(() -> Buckets.Fe).block(() -> FluidBlocks.fluidFe);
    public static ForgeFlowingFluid.Properties F2 = new ForgeFlowingFluid.Properties(() -> Sources.F2, () -> Flowings.F2, AttrBuilders.F2).bucket(() -> Buckets.F2).block(() -> FluidBlocks.fluidF2);
    public static ForgeFlowingFluid.Properties ConcentratedHydrochloricAcid = new ForgeFlowingFluid.Properties(() -> Sources.ConcentratedHydrochloricAcid, () -> Flowings.ConcentratedHydrochloricAcid, AttrBuilders.ConcentratedHydrochloricAcid).bucket(() -> Buckets.ConcentratedHydrochloricAcid).block(() -> FluidBlocks.fluidConcentratedHydrochloricAcid);
    public static ForgeFlowingFluid.Properties DiluteHydrochloricAcid = new ForgeFlowingFluid.Properties(() -> Sources.DiluteHydrochloricAcid, () -> Flowings.DiluteHydrochloricAcid, AttrBuilders.DiluteHydrochloricAcid).bucket(() -> Buckets.DiluteHydrochloricAcid).block(() -> FluidBlocks.fluidDiluteHydrochloricAcid);
    public static ForgeFlowingFluid.Properties I2 = new ForgeFlowingFluid.Properties(() -> Sources.I2, () -> Flowings.I2, AttrBuilders.I2).bucket(() -> Buckets.I2).block(() -> FluidBlocks.fluidI2);
    public static ForgeFlowingFluid.Properties HI = new ForgeFlowingFluid.Properties(() -> Sources.HI, () -> Flowings.HI, AttrBuilders.HI).bucket(() -> Buckets.HI).block(() -> FluidBlocks.fluidHI);
    public static ForgeFlowingFluid.Properties Br2 = new ForgeFlowingFluid.Properties(() -> Sources.Br2, () -> Flowings.Br2, AttrBuilders.Br2).bucket(() -> Buckets.Br2).block(() -> FluidBlocks.fluidBr2);
    public static ForgeFlowingFluid.Properties HBr = new ForgeFlowingFluid.Properties(() -> Sources.HBr, () -> Flowings.HBr, AttrBuilders.HBr).bucket(() -> Buckets.HBr).block(() -> FluidBlocks.fluidHBr);
    public static ForgeFlowingFluid.Properties HClO = new ForgeFlowingFluid.Properties(() -> Sources.HClO, () -> Flowings.HClO, AttrBuilders.HClO).bucket(() -> Buckets.HClO).block(() -> FluidBlocks.fluidHClO);
    public static ForgeFlowingFluid.Properties H2SO4 = new ForgeFlowingFluid.Properties(() -> Sources.H2SO4, () -> Flowings.h2so4, AttrBuilders.h2so4).bucket(() -> Buckets.h2so4).block(() -> FluidBlocks.fluidH2SO4);
    public static ForgeFlowingFluid.Properties H2SO3 = new ForgeFlowingFluid.Properties(() -> Sources.H2SO3, () -> Flowings.h2so3, AttrBuilders.h2so3).bucket(() -> Buckets.h2so3).block(() -> FluidBlocks.fluidH2SO3);
    public static ForgeFlowingFluid.Properties SO3 = new ForgeFlowingFluid.Properties(() -> Sources.SO3, () -> Flowings.so3, AttrBuilders.so3).bucket(() -> Buckets.so3).block(() -> FluidBlocks.fluidSO3);
    public static ForgeFlowingFluid.Properties SO2 = new ForgeFlowingFluid.Properties(() -> Sources.SO2, () -> Flowings.so2, AttrBuilders.so2).bucket(() -> Buckets.so2).block(() -> FluidBlocks.fluidSO2);
    public static ForgeFlowingFluid.Properties FluoroaluminicAcid = new ForgeFlowingFluid.Properties(() -> Sources.FluoroaluminicAcid, () -> Flowings.FluoroaluminicAcid, AttrBuilders.FluoroaluminicAcid).bucket(() -> Buckets.FluoroaluminicAcid).block(() -> FluidBlocks.fluidFluoroaluminicAcid);
    public static ForgeFlowingFluid.Properties HF = new ForgeFlowingFluid.Properties(() -> Sources.HF, () -> Flowings.hf, AttrBuilders.hf).bucket(() -> Buckets.hf).block(() -> FluidBlocks.fluidHF);
    public static ForgeFlowingFluid.Properties Na = new ForgeFlowingFluid.Properties(() -> Sources.Na, () -> Flowings.Na, AttrBuilders.Na).bucket(() -> Buckets.Na).block(() -> FluidBlocks.fluidNa);
    public static ForgeFlowingFluid.Properties Mg = new ForgeFlowingFluid.Properties(() -> Sources.Mg, () -> Flowings.Mg, AttrBuilders.Mg).bucket(() -> Buckets.Mg).block(() -> FluidBlocks.fluidMg);
    public static ForgeFlowingFluid.Properties SiCl4 = new ForgeFlowingFluid.Properties(() -> Sources.SiCl4, () -> Flowings.Sicl4, AttrBuilders.Sicl4).bucket(() -> Buckets.Sicl4).block(() -> FluidBlocks.fluidSiCl4);
    public static ForgeFlowingFluid.Properties HCl = new ForgeFlowingFluid.Properties(() -> Sources.HCl, () -> Flowings.HCl, AttrBuilders.HCl).bucket(() -> Buckets.HCl).block(() -> FluidBlocks.fluidHCl);
    public static ForgeFlowingFluid.Properties NaCl = new ForgeFlowingFluid.Properties(() -> Sources.NaCl, () -> Flowings.NaCl, AttrBuilders.NaCl).bucket(() -> Buckets.NaCl).block(() -> FluidBlocks.fluidNaCl);
    public static ForgeFlowingFluid.Properties MgCl2 = new ForgeFlowingFluid.Properties(() -> Sources.MgCl2, () -> Flowings.MgCl2, AttrBuilders.MgCl2).bucket(() -> Buckets.MgCl2).block(() -> FluidBlocks.fluidMgCl2);
    public static ForgeFlowingFluid.Properties AlCl3 = new ForgeFlowingFluid.Properties(() -> Sources.AlCl3, () -> Flowings.AlCl3s, AttrBuilders.AlCl3s).bucket(() -> Buckets.AlCl3s).block(() -> FluidBlocks.fluidAlCl3);
    public static ForgeFlowingFluid.Properties NaClSolutionConcentrated = new ForgeFlowingFluid.Properties(() -> Sources.NaClSolutionConcentrated, () -> Flowings.NaClSolutionConcentrated, AttrBuilders.NaClSolutionConcentrated).bucket(() -> Buckets.NaClSolutionConcentrated).block(() -> FluidBlocks.fluidNaClSolutionConcentrated);
    public static ForgeFlowingFluid.Properties seaWater = new ForgeFlowingFluid.Properties(() -> Sources.seaWater, () -> Flowings.seawater, AttrBuilders.seawater).bucket(() -> Buckets.seawater).block(() -> FluidBlocks.fluidSeaWater);
    public static ForgeFlowingFluid.Properties NaAlO2 = new ForgeFlowingFluid.Properties(() -> Sources.NaAlO2, () -> Flowings.NaAlO2, AttrBuilders.NaAlO2).bucket(() -> Buckets.NaAlO2).block(() -> FluidBlocks.fluidNaAlO2);
    public static ForgeFlowingFluid.Properties Cu_NO3_2 = new ForgeFlowingFluid.Properties(() -> Sources.Cu_no3_2, () -> Flowings.Cu_no3_2, AttrBuilders.Cu_no3_2).bucket(() -> Buckets.Cu_no3_2).block(() -> FluidBlocks.fluidCu_NO3_2);
    public static ForgeFlowingFluid.Properties NaClSolutionDilute = new ForgeFlowingFluid.Properties(() -> Sources.NaClSolutionDilute, () -> Flowings.NaClSolutionDilute, AttrBuilders.NaClSolutionDilute).bucket(() -> Buckets.NaClSolutionDilute).block(() -> FluidBlocks.fluidNaClSolutionDilute);
    public static ForgeFlowingFluid.Properties MagnesiumChlorideSolution  = new ForgeFlowingFluid.Properties(() -> Sources.MagnesiumChlorideSolution , () -> Flowings.MagnesiumChlorideSolution , AttrBuilders.MagnesiumChlorideSolution ).bucket(() -> Buckets.MagnesiumChlorideSolution ).block(() -> FluidBlocks.fluidMagnesiumChlorideSolution);
    public static ForgeFlowingFluid.Properties NH4Cl = new ForgeFlowingFluid.Properties(() -> Sources.NH4Cl, () -> Flowings.NH4Cl, AttrBuilders.NH4Cl).bucket(() -> Buckets.NH4Cl).block(() -> FluidBlocks.fluidNH4Cl);
    public static ForgeFlowingFluid.Properties NaOH = new ForgeFlowingFluid.Properties(() -> Sources.NaOH, () -> Flowings.Naoh, AttrBuilders.Naoh).bucket(() -> Buckets.Naoh).block(() -> FluidBlocks.fluidNaOH);
    public static ForgeFlowingFluid.Properties NaNO3 = new ForgeFlowingFluid.Properties(() -> Sources.NaNO3, () -> Flowings.NaNo3, AttrBuilders.NaNo3).bucket(() -> Buckets.NaNo3).block(() -> FluidBlocks.fluidNaNO3);
    public static ForgeFlowingFluid.Properties H = new ForgeFlowingFluid.Properties(() -> Sources.H, () -> Flowings.H, AttrBuilders.H).bucket(() -> Buckets.H).block(() -> FluidBlocks.fluidH);
    public static ForgeFlowingFluid.Properties steam = new ForgeFlowingFluid.Properties(() -> Sources.steam, () -> Flowings.steam, AttrBuilders.steam).bucket(() -> Buckets.steam).block(() -> FluidBlocks.fluidSteam);
    public static ForgeFlowingFluid.Properties waterDistilled = new ForgeFlowingFluid.Properties(() -> Sources.waterDistilled, () -> Flowings.waterDistilled, AttrBuilders.waterDistilled).bucket(() -> Buckets.waterDistilled).block(() -> FluidBlocks.fluidWaterDistilled);
    public static ForgeFlowingFluid.Properties butter = new ForgeFlowingFluid.Properties(() -> Sources.butter, () -> Flowings.butter, AttrBuilders.butter).bucket(() -> Buckets.butter).block(() -> FluidBlocks.fluidButter);
    public static ForgeFlowingFluid.Properties acetylene = new ForgeFlowingFluid.Properties(() -> Sources.acetylene, () -> Flowings.acetylene, AttrBuilders.acetylene).bucket(() -> Buckets.acetylene).block(() -> FluidBlocks.fluidAcetylene);
    public static ForgeFlowingFluid.Properties ethylene = new ForgeFlowingFluid.Properties(() -> Sources.ethylene, () -> Flowings.ethylene, AttrBuilders.ethylene).bucket(() -> Buckets.ethylene).block(() -> FluidBlocks.fluidEthylene);
    public static ForgeFlowingFluid.Properties CO = new ForgeFlowingFluid.Properties(() -> Sources.CO, () -> Flowings.co, AttrBuilders.co).bucket(() -> Buckets.co).block(() -> FluidBlocks.fluidCO);
    public static ForgeFlowingFluid.Properties ethanol = new ForgeFlowingFluid.Properties(() -> Sources.ethanol, () -> Flowings.ethanol, AttrBuilders.ethanol).bucket(() -> Buckets.ethanol).block(() -> FluidBlocks.fluidEthanol);
    public static ForgeFlowingFluid.Properties calciumHydroxide = new ForgeFlowingFluid.Properties(() -> Sources.calciumHydroxide, () -> Flowings.calciumHydroxide, AttrBuilders.calciumHydroxide).bucket(() -> Buckets.calciumHydroxide).block(() -> FluidBlocks.fluidCalciumHydroxide);
    public static ForgeFlowingFluid.Properties calmogastrin = new ForgeFlowingFluid.Properties(() -> Sources.calmogastrin, () -> Flowings.calmogastrin, AttrBuilders.calmogastrin).bucket(() -> Buckets.calmogastrin).block(() -> FluidBlocks.fluidCalmogastrin);
    public static ForgeFlowingFluid.Properties methane = new ForgeFlowingFluid.Properties(() -> Sources.methane, () -> Flowings.methane, AttrBuilders.methane).bucket(() -> Buckets.methane).block(() -> FluidBlocks.fluidMethane);
    public static ForgeFlowingFluid.Properties ethane = new ForgeFlowingFluid.Properties(() -> Sources.ethane, () -> Flowings.ethane, AttrBuilders.ethane).bucket(() -> Buckets.ethane).block(() -> FluidBlocks.fluidEthane);
    public static ForgeFlowingFluid.Properties chlorine = new ForgeFlowingFluid.Properties(() -> Sources.chlorine, () -> Flowings.chlorine, AttrBuilders.chlorine).bucket(() -> Buckets.chlorine).block(() -> FluidBlocks.fluidChlorine);
    public static ForgeFlowingFluid.Properties concentratedSulfuricAcid = new ForgeFlowingFluid.Properties(() -> Sources.concentratedSulfuricAcid, () -> Flowings.concentratedSulfuricAcid, AttrBuilders.concentratedSulfuricAcid).bucket(() -> Buckets.concentratedSulfuricAcid).block(() -> FluidBlocks.fluidConcentratedSulfuricAcid);
    public static ForgeFlowingFluid.Properties diluteSulfuricAcid = new ForgeFlowingFluid.Properties(() -> Sources.diluteSulfuricAcid, () -> Flowings.diluteSulfuricAcid, AttrBuilders.diluteSulfuricAcid).bucket(() -> Buckets.diluteSulfuricAcid).block(() -> FluidBlocks.fluidDiluteSulfuricAcid);
    public static ForgeFlowingFluid.Properties nitrogen = new ForgeFlowingFluid.Properties(() -> Sources.nitrogen, () -> Flowings.nitrogen, AttrBuilders.nitrogen).bucket(() -> Buckets.nitrogen).block(() -> FluidBlocks.fluidNitrogen);
    public static ForgeFlowingFluid.Properties Al = new ForgeFlowingFluid.Properties(() -> Sources.Al, () -> Flowings.Al, AttrBuilders.Al).bucket(() -> Buckets.Al).block(() -> FluidBlocks.fluidAl);
    public static ForgeFlowingFluid.Properties Na3AlF6 = new ForgeFlowingFluid.Properties(() -> Sources.Na3AlF6, () -> Flowings.Na3AlF6, AttrBuilders.Na3AlF6).bucket(() -> Buckets.Na3AlF6).block(() -> FluidBlocks.fluidNa3AlF6);
    public static ForgeFlowingFluid.Properties ammonia = new ForgeFlowingFluid.Properties(() -> Sources.ammonia, () -> Flowings.ammonia, AttrBuilders.ammonia).bucket(() -> Buckets.ammonia).block(() -> FluidBlocks.fluidAmmonia);
    public static ForgeFlowingFluid.Properties oxygen = new ForgeFlowingFluid.Properties(() -> Sources.oxygen, () -> Flowings.oxygen, AttrBuilders.oxygen).bucket(() -> Buckets.oxygen).block(() -> FluidBlocks.fluidOxygen);
    public static ForgeFlowingFluid.Properties air = new ForgeFlowingFluid.Properties(() -> Sources.air, () -> Flowings.air, AttrBuilders.air).bucket(() -> Buckets.air).block(() -> FluidBlocks.fluidAir);
    public static ForgeFlowingFluid.Properties Al2O3_Na3AlF6 = new ForgeFlowingFluid.Properties(() -> Sources.Al2O3_Na3AlF6, () -> Flowings.Al2O3_Na3AlF6, AttrBuilders.Al2O3_Na3AlF6).bucket(() -> Buckets.Al2O3_Na3AlF6).block(() -> FluidBlocks.fluidAl2O3_Na3AlF6);
    public static ForgeFlowingFluid.Properties rareGases = new ForgeFlowingFluid.Properties(() -> Sources.rareGases, () -> Flowings.rareGases, AttrBuilders.rareGases).bucket(() -> Buckets.rareGases).block(() -> FluidBlocks.fluidRareGases);
    public static ForgeFlowingFluid.Properties CO2 = new ForgeFlowingFluid.Properties(() -> Sources.CO2, () -> Flowings.co2, AttrBuilders.co2).bucket(() -> Buckets.co2).block(() -> FluidBlocks.fluidCO2);
    public static ForgeFlowingFluid.Properties HNO3 = new ForgeFlowingFluid.Properties(() -> Sources.HNO3, () -> Flowings.hno3, AttrBuilders.hno3).bucket(() -> Buckets.hno3).block(() -> FluidBlocks.fluidHNO3);
    public static ForgeFlowingFluid.Properties HNO3Concentrated = new ForgeFlowingFluid.Properties(() -> Sources.HNO3Concentrated, () -> Flowings.nongHNO3, AttrBuilders.nongHNO3).bucket(() -> Buckets.nongHNO3).block(() -> FluidBlocks.fluidHNO3Concentrated);
    public static ForgeFlowingFluid.Properties HNO3Dilute = new ForgeFlowingFluid.Properties(() -> Sources.HNO3Dilute, () -> Flowings.xiHNO3, AttrBuilders.xiHNO3).bucket(() -> Buckets.xiHNO3).block(() -> FluidBlocks.fluidHNO3Dilute);
    public static ForgeFlowingFluid.Properties NO = new ForgeFlowingFluid.Properties(() -> Sources.NO, () -> Flowings.no, AttrBuilders.no).bucket(() -> Buckets.no).block(() -> FluidBlocks.fluidNO);
    public static ForgeFlowingFluid.Properties NO2 = new ForgeFlowingFluid.Properties(() -> Sources.NO2, () -> Flowings.no2, AttrBuilders.no2).bucket(() -> Buckets.no2).block(() -> FluidBlocks.fluidNO2);
    public static ForgeFlowingFluid.Properties O3 = new ForgeFlowingFluid.Properties(() -> Sources.O3, () -> Flowings.o3, AttrBuilders.o3).bucket(() -> Buckets.o3).block(() -> FluidBlocks.fluidO3);
}
