package com.elementtimes.tutorial.common.init;

import com.elementtimes.tutorial.common.item.*;

import net.minecraft.item.Item;

public class ElementtimesItems {
    public static final Item Fiveelements = new Fiveelements();
    public static final Item Endelement = new Endelement();
    public static final Item Soilelement = new Soilelement();
    public static final Item Woodelement = new Woodelement();
    public static final Item Waterelement = new Waterelement();
    public static final Item Fireelement = new Fireelement();
    public static final Item Goldelement = new Goldelement();
    public static final Item Saplingessence = new Saplingessence();
    public static final Item Cropessence = new Cropessence();
    public static final Item Elementsword = new Elementsword();
    public static final Item Elementaxe = new Elementaxe();
    public static final Item Elementpickaxe = new Elementpickaxe();
    public static final Item Starchpowder = new Starchpowder();
    public static final Item Amylum = new Amylum();
    public static final Item Puremeat = new Puremeat();
    public static final Item Corn = new Corn();
    public static final Item Bakedcorn = new Bakedcorn();
    public static final Item Stoneingot = new Stoneingot();
    public static final Item Steelingot = new Steelingot();
    public static final Item Calciumcarbonate = new Calciumcarbonate();
    public static final Item Calciumoxide = new Calciumoxide();
    public static final Item Ingotcolumn = new Ingotcolumn();
    public static final Item Concrete = new Concrete();
    public static final Item ElementSleeveHelmet = new ElementSleeveHelmet();
    public static final Item ElementSleeveBody = new ElementSleeveBody();
    public static final Item ElementSleeveLeggings = new ElementSleeveLeggings();
    public static final Item ElementSleeveBoots = new ElementSleeveBoots();
    public static final Item PlatinumSleeveHelmet = new PlatinumSleeveHelmet();
    public static final Item PlatinumSleeveBody = new PlatinumSleeveBody();
    public static final Item PlatinumSleeveLeggings = new PlatinumSleeveLeggings();
    public static final Item PlatinumSleeveBoots = new PlatinumSleeveBoots();
    public static final Item Copper = new Copper();
    public static final Item Greenstonepowder = new Greenstonepowder();
    public static final Item Redstonepowder = new Redstonepowder();
    public static final Item Bluestonepowder = new Bluestonepowder();
    public static final Item Ironpower = new Ironpower();
    public static final Item Goldpowder = new Goldpowder();
    public static final Item Coalpowder = new Coalpowder();
    public static final Item Diamondpowder = new Diamondpowder();
    public static final Item Copperpowder = new Copperpowder();
    public static final Item Spanner = new Spanner();
    public static final Item Twiningsuncompound = new Twiningsuncompound();
    public static final Item Intermediaterubbingsuncompound = new Intermediaterubbingsuncompound();
    public static final Item Largerubbingsuncompound = new Largerubbingsuncompound();
    public static final Item Photoelement = new Photoelement();
    public static final Item Quartzpowder = new Quartzpowder();
    public static final Item Bighammer = new Bighammer();
    public static final Item Smallhammer = new Smallhammer();
    public static final Item Cornbroth = new Cornbroth();
    public static final Item Money = new Money();
    public static final Item Sulfurorepowder = new Sulfurorepowder();   
    public static final Item Sulfurpowder = new Sulfurpowder();
    public static final Item Sucrosecharcoal = new Sucrosecharcoal();
    public static final Item Platinumingot = new Platinumingot();
    public static final Item Platinumorepowder = new Platinumorepowder();
    public static final Item Diamondingot = new Diamondingot();
    public static final Item Hydrogen = new Hydrogen();
    public static final Item Steam = new Steam();
    public static final Item Sulfitesolution = new Sulfitesolution();
    public static final Item Sulphuricacid = new Sulphuricacid();
    public static final Item Sodiumsulfitesolution = new Sodiumsulfitesolution();
    public static final Item Elementshovel = new Elementshovel();
    public static final Item Elementhoe = new Elementhoe();
    public static final Item Platinumsword = new Platinumsword();
    public static final Item Platinumhoe = new Platinumhoe();
    public static final Item Platinumshovel = new Platinumshovel();
    public static final Item Platinumaxe = new Platinumaxe();
    public static final Item Platinumpick = new Platinumpick();
}
